# Generated by Django 4.2.2 on 2023-06-08 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slno', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('desc', models.CharField(max_length=200)),
            ],
        ),
    ]
